### ISSUE TITLE
URL for interactive video is not shown as a field when I try to create new interactive video in “Interactive Content”

### ISSUE THREAD

**Issue by Dimitrispant** [success4all-eu/learning-platform#2]
URL for interactive video is not shown as a field when I try to create new interactive video in “Interactive Content”

1. Go to a selected course
2. Click on 'Add an activity or resource'
3. Select “Interactive Content”
4. Select Interactive Video for creating new
5. The Field for adding a video URL is not shown

**Screenshots**
![image](https://user-images.githubusercontent.com/13375110/171000172-9144aab4-5a49-463c-a755-a1e328a15a1f.png)

Desktop (please complete the following information):

OS: Windows 10 21H2
Browser Edge
Version 101.0.1210.53 (Official build) (64-bit)

**Comment by michzimny** [comment]
@Dimitrispant, thanks for reporting.

It has been solved. Please check.

Relevant H5P engines needed to be updated within the plugin.
