### ISSUE TITLE
Banner in the home page is cut

### ISSUE THREAD

**Issue by Dimitrispant** [success4all-eu/learning-platform#3]
Banner in the home page is cut and is now shown properly. 

1. Go to the homepage

**Expected behavior**
Banner should be responsive

**Screenshots**
![image](https://user-images.githubusercontent.com/13375110/171000832-7d9d8196-dccc-4d76-80e8-225f97daf84b.png)

Desktop (please complete the following information):

OS: Windows 10 21H2
Browser Edge
Version 101.0.1210.53 (Official build) (64-bit)

**Additional context**
It seems that this issue is in resolution under 1300 width.

**Comment by michzimny** [comment]
Thanks for reporting. The image is now replaced with another one, which looks better when trimmed.
