### ISSUE TITLE
The link to the Announcements forum is unclear

### ISSUE THREAD

**Issue by gtoffoli** [success4all-eu/learning-platform#5]
For testing purposes, I created the course _Resources aggregration demo_. 

In its homepage, below the title and above the topics list, the link occurs to what seems a forum. 
From its label, _Announcements_, I deduce that the link provides an opportunity for publishing information on the course; why not make this fact explicit?
I also presume that this is a global forum (accessible outside the specific course), but this should be made more clear too, in my view.

**Comment by michzimny** [comment]
@gtoffoli, thank you for reporting.

What do you mean by making this explicit? Do you suggest to reformulate the label of that link? To what?

It is not a global forum. It is specific to the course.

You, as the course owner, may delete it or move it, or rename it, as you wish. It is just by default added to every new course.

**Comment by gtoffoli** [comment]
@michzimny Since I'm not a Moodle user, it wasn't evident to me that
- it is a forum inside an untitled section of the course itself (but I guessed this before your reply)
- it is added by default on course creation.

**Comment by michzimny** [comment]
Thanks for replying. 

Shall we then consider this issue closed, or do you have any suggestions on how to improve the user experience regarding this?

**Comment by gtoffoli** [comment]
For me it is ok and you may close the issue.
