### ISSUE TITLE
The course description disappears?

### ISSUE THREAD

**Issue by gtoffoli** [success4all-eu/learning-platform#6]
If I am not wrong, when I created the test course _Resources aggregration demo,_ I had the opportunity of providing a "description" for it, besides it title, but no more can I find it.

**Comment by michzimny** [comment]
It is visible to students when trying to enrol to your course:

![image](https://user-images.githubusercontent.com/1483196/179728015-fa905465-3568-4e04-b139-9b27f710ad50.png)

Does it address your concerns? If not, please reopen.

**Comment by gtoffoli** [comment]
> It is visible to students when trying to enrol to your course

Yes, but I, as a teacher, cannot find a way of editing the description.

**Comment by kdostatnia** [comment]
Please try this:
![image](https://user-images.githubusercontent.com/106582747/180152200-bff67ecb-fd53-4d48-a38e-f5b5859f017b.png)

**Comment by gtoffoli** [comment]
Ok, thank you.
I wasn't able to view that screen, possibly I don't own proper rights.
However, I reached a comprehensive setting/editing view for my course following this path:

`Site administration -> Courses -> Manage courses and categories -> test [category, or search by name] -> Resources aggregration demo [edit icon]`

Please take into account that I'm not an expert user of Moodle, and that most teachers are expected to be even less familiar with it than I am.
